language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
services:
  - docker
script:
- npm run lint:fix
- npm run build
- npm run test
- npm start & wait-on http://localhost:3000
- $(npm bin)/cypress run --record --key 3c488038-b995-46f1-b915-512f43a83841
deploy:
  - provider: script
    skip_cleanup: true
    script: chmod +x ./scripts/* && ./scripts/deploy.sh sweng-devops
    on:
      all_branches: true
notifications:
  slack: group26-sweng:m9L41HvII2Mr7aOkFuGwWCF3
