language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm run build
true:
  branch: master
deploy:
  provider: heroku
  api_key:
    secure: D8bbO/kbiMbyPwkKwRClx4xA5UvJdvQnXJuwWu4c20qmSYDOQEbjNPbuuk4wKGh4u1wyWzRi3f+xNUR2TZsXQSz36ejAD1MJrbhksW/UNjq9bwzi0Ry1/ZrzjRdNh88k3jNrt3TB+mYelNfRHyTKg7OY1hIgAxAbxaHoy8tKB8ojHJ7kmWOQnCUyIyRQ8aTuPJqliavNoZuqtUVGHLT98U4AR3kLrYKB5YtpoPwRY+zRud8e3OZPny0+IQNb7Jk5G4GkJkBiBNKtkY4tmEdhajdBUFT2YYiusMOGDbwRL6qyR06oTuV0nejJr/5Bx/BdPgrK/v5fD393BQAeJxqe+uZo9kzgd6jgaheXxpA/Uxys8y4vpE6H+YRxprS5PA9hnXXuTuzvIBZWHTwS33iIbM5n2IGvX4i5Oar6b1FVPdnxJFER4F/8L0nxi/oxvpx173koU/EQJBgKuijJTUinMlQtLMYAI2MNX1tRApASr+rRMTQXVCo0cWs+tCZLmo/ZNDNvGyAzvsw/Gir2csNDG7HDQWdm4HJFt7e2dG20KdV7iQFfR1T2mTlgCLNos9i4dyxbN7bo3DrN9WVFtlIPyrtB3btZ9b3PijEIjZHxx3182esH6jz6w/hcKtUmad2Bb8jIPf0KHHn0Ec/o81g6R+be+K/1G/4sizuBnB5TQ5U=
  app: react-app-develop
  on: develop
