language: node_js
os: linux
dist: xenial
node_js:
- stable
cache:
  directories:
  - node_modules
  timeout: 3
services:
  - docker
notifications:
  slack: group26-sweng:m9L41HvII2Mr7aOkFuGwWCF3

stages:
  - build
  - analyze
  - bake
  - deploy to develop
  # - test
  - name: deploy to production
    if: branch = master

jobs:
  include:
    - stage: build
      script: 
      - npm run build
    - stage: analyze
      script: 
        - npm run lint:fix
        - npm run test
        - npm install wait-on
        - npm start & wait-on http://localhost:3000
        - $(npm bin)/cypress run --record --key 3c488038-b995-46f1-b915-512f43a83841
    - stage: bake
      install: chmod +x ./scripts/* && ./scripts/bake_install.sh develop
      script: 
        - chmod +x ./scripts/*
        - ./scripts/build_docker_image.sh sweng-devops
    - stage: deploy to develop
      install: chmod +x ./scripts/* && ./scripts/install.sh develop
      script: skip
      deploy:
        - provider: script
          skip_cleanup: true
          script: chmod +x ./scripts/* && ./scripts/deploy.sh develop
          on:
            all_branches: true
    # - stage: test
    #   script: skip
    - stage: deploy to production
      install: chmod +x ./scripts/* && ./scripts/install.sh production
      script: skip
      deploy:
        - provider: script
          script: chmod +x ./scripts/* && ./scripts/deploy.sh production
          on:
            branch: master