apiVersion: v1
kind: Service
metadata:
  name: sweng-devops
  labels:
    name: sweng-devops
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30000
      name: http
  selector:
    app: sweng-devops
    deployment: ${DEPLOYMENT}